### ISSUE TITLE
belt

### ISSUE THREAD

**Issue by agievich** [Roman-Oliynykov/ciphers-speed#1]
Уважаемый Роман,

Обращаю Ваше внимание на более эффективную реализацию Belt: 
https://github.com/agievich/bee2/blob/master/src/crypto/belt.c.

Сергей Агиевич

**Comment by Roman-Oliynykov** [comment]
Добрый день!

Ссылку получил, заменим в нашей реализации (планирую в течение месяца).

Большое спасибо за сотрудничество!

**Comment by Roman-Oliynykov** [comment]
Более эффективную реализацию добавили, скорость Belt увеличилась более, чем на 100 Мбит/с. Исходники, скомпилированную версию и данные замеров обновили.
Большое спасибо за сотрудничество!
